const Content = () => {
    return (
        <div className="flex justify-center mt-6">
            <div className="max-w-xl">
            <h1 className="font-semibold text-lg">Title</h1>
            <p className="my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquam, aperiam assumenda autem cum eligendi eveniet illo natus nulla omnis quas sapiente tenetur voluptate? Commodi expedita magnam nemo, quos reprehenderit tenetur vero! Aperiam commodi consectetur laboriosam porro, quaerat quia repellendus repudiandae saepe ullam vel. Atque corporis cum dignissimos facilis, iusto labore nulla numquam provident, quam rem rerum saepe! Aperiam architecto atque aut consectetur corporis, dolor dolores ducimus ea, error et ex facilis fugit hic mollitia nam nobis nulla possimus provident, quas quasi quia quidem quisquam recusandae reiciendis reprehenderit similique voluptatem? Commodi illo incidunt labore laborum maxime nulla optio possimus sequi.</p>
            <p className="my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquam, aperiam assumenda autem cum eligendi eveniet illo natus nulla omnis quas sapiente tenetur voluptate? Commodi expedita magnam nemo, quos reprehenderit tenetur vero! Aperiam commodi consectetur laboriosam porro, quaerat quia repellendus repudiandae saepe ullam vel. Atque corporis cum dignissimos facilis, iusto labore nulla numquam provident, quam rem rerum saepe! Aperiam architecto atque aut consectetur corporis, dolor dolores ducimus ea, error et ex facilis fugit hic mollitia nam nobis nulla possimus provident, quas quasi quia quidem quisquam recusandae reiciendis reprehenderit similique voluptatem? Commodi illo incidunt labore laborum maxime nulla optio possimus sequi.</p>
            <p className="my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquam, aperiam assumenda autem cum eligendi eveniet illo natus nulla omnis quas sapiente tenetur voluptate? Commodi expedita magnam nemo, quos reprehenderit tenetur vero! Aperiam commodi consectetur laboriosam porro, quaerat quia repellendus repudiandae saepe ullam vel. Atque corporis cum dignissimos facilis, iusto labore nulla numquam provident, quam rem rerum saepe! Aperiam architecto atque aut consectetur corporis, dolor dolores ducimus ea, error et ex facilis fugit hic mollitia nam nobis nulla possimus provident, quas quasi quia quidem quisquam recusandae reiciendis reprehenderit similique voluptatem? Commodi illo incidunt labore laborum maxime nulla optio possimus sequi.</p>
            <p className="my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquam, aperiam assumenda autem cum eligendi eveniet illo natus nulla omnis quas sapiente tenetur voluptate? Commodi expedita magnam nemo, quos reprehenderit tenetur vero! Aperiam commodi consectetur laboriosam porro, quaerat quia repellendus repudiandae saepe ullam vel. Atque corporis cum dignissimos facilis, iusto labore nulla numquam provident, quam rem rerum saepe! Aperiam architecto atque aut consectetur corporis, dolor dolores ducimus ea, error et ex facilis fugit hic mollitia nam nobis nulla possimus provident, quas quasi quia quidem quisquam recusandae reiciendis reprehenderit similique voluptatem? Commodi illo incidunt labore laborum maxime nulla optio possimus sequi.</p>
            <p className="my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquam, aperiam assumenda autem cum eligendi eveniet illo natus nulla omnis quas sapiente tenetur voluptate? Commodi expedita magnam nemo, quos reprehenderit tenetur vero! Aperiam commodi consectetur laboriosam porro, quaerat quia repellendus repudiandae saepe ullam vel. Atque corporis cum dignissimos facilis, iusto labore nulla numquam provident, quam rem rerum saepe! Aperiam architecto atque aut consectetur corporis, dolor dolores ducimus ea, error et ex facilis fugit hic mollitia nam nobis nulla possimus provident, quas quasi quia quidem quisquam recusandae reiciendis reprehenderit similique voluptatem? Commodi illo incidunt labore laborum maxime nulla optio possimus sequi.</p>
            <p className="my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquam, aperiam assumenda autem cum eligendi eveniet illo natus nulla omnis quas sapiente tenetur voluptate? Commodi expedita magnam nemo, quos reprehenderit tenetur vero! Aperiam commodi consectetur laboriosam porro, quaerat quia repellendus repudiandae saepe ullam vel. Atque corporis cum dignissimos facilis, iusto labore nulla numquam provident, quam rem rerum saepe! Aperiam architecto atque aut consectetur corporis, dolor dolores ducimus ea, error et ex facilis fugit hic mollitia nam nobis nulla possimus provident, quas quasi quia quidem quisquam recusandae reiciendis reprehenderit similique voluptatem? Commodi illo incidunt labore laborum maxime nulla optio possimus sequi.</p>
            <p className="my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquam, aperiam assumenda autem cum eligendi eveniet illo natus nulla omnis quas sapiente tenetur voluptate? Commodi expedita magnam nemo, quos reprehenderit tenetur vero! Aperiam commodi consectetur laboriosam porro, quaerat quia repellendus repudiandae saepe ullam vel. Atque corporis cum dignissimos facilis, iusto labore nulla numquam provident, quam rem rerum saepe! Aperiam architecto atque aut consectetur corporis, dolor dolores ducimus ea, error et ex facilis fugit hic mollitia nam nobis nulla possimus provident, quas quasi quia quidem quisquam recusandae reiciendis reprehenderit similique voluptatem? Commodi illo incidunt labore laborum maxime nulla optio possimus sequi.</p>
            <p className="my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquam, aperiam assumenda autem cum eligendi eveniet illo natus nulla omnis quas sapiente tenetur voluptate? Commodi expedita magnam nemo, quos reprehenderit tenetur vero! Aperiam commodi consectetur laboriosam porro, quaerat quia repellendus repudiandae saepe ullam vel. Atque corporis cum dignissimos facilis, iusto labore nulla numquam provident, quam rem rerum saepe! Aperiam architecto atque aut consectetur corporis, dolor dolores ducimus ea, error et ex facilis fugit hic mollitia nam nobis nulla possimus provident, quas quasi quia quidem quisquam recusandae reiciendis reprehenderit similique voluptatem? Commodi illo incidunt labore laborum maxime nulla optio possimus sequi.</p>
            <p className="my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquam, aperiam assumenda autem cum eligendi eveniet illo natus nulla omnis quas sapiente tenetur voluptate? Commodi expedita magnam nemo, quos reprehenderit tenetur vero! Aperiam commodi consectetur laboriosam porro, quaerat quia repellendus repudiandae saepe ullam vel. Atque corporis cum dignissimos facilis, iusto labore nulla numquam provident, quam rem rerum saepe! Aperiam architecto atque aut consectetur corporis, dolor dolores ducimus ea, error et ex facilis fugit hic mollitia nam nobis nulla possimus provident, quas quasi quia quidem quisquam recusandae reiciendis reprehenderit similique voluptatem? Commodi illo incidunt labore laborum maxime nulla optio possimus sequi.</p>
            <p className="my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquam, aperiam assumenda autem cum eligendi eveniet illo natus nulla omnis quas sapiente tenetur voluptate? Commodi expedita magnam nemo, quos reprehenderit tenetur vero! Aperiam commodi consectetur laboriosam porro, quaerat quia repellendus repudiandae saepe ullam vel. Atque corporis cum dignissimos facilis, iusto labore nulla numquam provident, quam rem rerum saepe! Aperiam architecto atque aut consectetur corporis, dolor dolores ducimus ea, error et ex facilis fugit hic mollitia nam nobis nulla possimus provident, quas quasi quia quidem quisquam recusandae reiciendis reprehenderit similique voluptatem? Commodi illo incidunt labore laborum maxime nulla optio possimus sequi.</p>
            <p className="my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquam, aperiam assumenda autem cum eligendi eveniet illo natus nulla omnis quas sapiente tenetur voluptate? Commodi expedita magnam nemo, quos reprehenderit tenetur vero! Aperiam commodi consectetur laboriosam porro, quaerat quia repellendus repudiandae saepe ullam vel. Atque corporis cum dignissimos facilis, iusto labore nulla numquam provident, quam rem rerum saepe! Aperiam architecto atque aut consectetur corporis, dolor dolores ducimus ea, error et ex facilis fugit hic mollitia nam nobis nulla possimus provident, quas quasi quia quidem quisquam recusandae reiciendis reprehenderit similique voluptatem? Commodi illo incidunt labore laborum maxime nulla optio possimus sequi.</p>
        </div></div>
    );
};

export default Content;